name: Super-Linter
 
on:
  pull_request: # Runs on pull requests
  push:         # Runs on pushes to the default branch
    branches:
      - main    # Adjust to your default branch name
 
jobs:
  lint:
    runs-on: ubuntu-latest
 
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
 
      # Step 2: Run Super-Linter
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          # Enable Python linting
          VALIDATE_PYTHON: true
          # Set the default branch for comparison
          DEFAULT_BRANCH: main
          # Required GitHub token for the linter
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
